[smtp]
server = "smtp.gmail.com"
port = 587

[general]
poll_interval = 120
purchase_cutoff_minutes = 120
api_base_url = "https://brn-ybus-pubapi.sa.cz/restapi"

[auth]
credit_enabled = true
credit_user = ""
credit_password = ""
