/*
RegioJet's Affiliate API Reference

The RegioJet\\'s Affiliate API is a set of endpoints that help your application integrate with RegioJet.  The API is organized arount [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API uses standard HTTP methods, authentication, and status codes.  # Authentication Authentication to the API is performed via [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication) for all endpoints listed in this documentation with the exception of `/users/authenticate`, which uses bearer token.  API requests without authentication will fail.  All API requests must be made over [HTTPS](https://en.wikipedia.org/wiki/HTTPS).  # Errors  RegioJet uses conventional HTTP status codes in responses to indicate the success or failure of an API request.  In general:   * `2xx` codes indicate success;   * `4xx` codes indicate an error that failed given the information provided in request.   * `5xx` codes indicate an error with RegioJet's servers.

API version: 1.1.0
Contact: developers@studentagency.cz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TicketState * `USED` - driven ticket * `VALID` - Valid and paid ticket * `UNPAID` - Unpaid reservation * `CANCELED` - Canceled by user (soft-booking) * `DELETED` - Canceled by user (hard-booking) * `EXPIRED` - Expirated soft-booking which cant be bought anymore * `TO_BE_EXPIRED` - Expirated soft-booking which werent be able to finish by system
type TicketState string

// List of TicketState
const (
	USED          TicketState = "USED"
	VALID         TicketState = "VALID"
	UNPAID        TicketState = "UNPAID"
	CANCELED      TicketState = "CANCELED"
	DELETED       TicketState = "DELETED"
	EXPIRED       TicketState = "EXPIRED"
	TO_BE_EXPIRED TicketState = "TO_BE_EXPIRED"
)

// All allowed values of TicketState enum
var AllowedTicketStateEnumValues = []TicketState{
	"USED",
	"VALID",
	"UNPAID",
	"CANCELED",
	"DELETED",
	"EXPIRED",
	"TO_BE_EXPIRED",
}

func (v *TicketState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TicketState(value)
	for _, existing := range AllowedTicketStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TicketState", value)
}

// NewTicketStateFromValue returns a pointer to a valid TicketState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTicketStateFromValue(v string) (*TicketState, error) {
	ev := TicketState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TicketState: valid values are %v", v, AllowedTicketStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TicketState) IsValid() bool {
	for _, existing := range AllowedTicketStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TicketState value
func (v TicketState) Ptr() *TicketState {
	return &v
}

type NullableTicketState struct {
	value *TicketState
	isSet bool
}

func (v NullableTicketState) Get() *TicketState {
	return v.value
}

func (v *NullableTicketState) Set(val *TicketState) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketState) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketState(val *TicketState) *NullableTicketState {
	return &NullableTicketState{value: val, isSet: true}
}

func (v NullableTicketState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
