/*
RegioJet's Affiliate API Reference

The RegioJet\\'s Affiliate API is a set of endpoints that help your application integrate with RegioJet.  The API is organized arount [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API uses standard HTTP methods, authentication, and status codes.  # Authentication Authentication to the API is performed via [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication) for all endpoints listed in this documentation with the exception of `/users/authenticate`, which uses bearer token.  API requests without authentication will fail.  All API requests must be made over [HTTPS](https://en.wikipedia.org/wiki/HTTPS).  # Errors  RegioJet uses conventional HTTP status codes in responses to indicate the success or failure of an API request.  In general:   * `2xx` codes indicate success;   * `4xx` codes indicate an error that failed given the information provided in request.   * `5xx` codes indicate an error with RegioJet's servers.

API version: 1.1.0
Contact: developers@studentagency.cz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SimpleSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimpleSection{}

// SimpleSection struct for SimpleSection
type SimpleSection struct {
	SectionId int64 `json:"sectionId"`
	// Valid station ID (city ID unsupported at this level)
	FromStationId int64 `json:"fromStationId"`
	// Valid station ID (city ID unsupported at this level)
	ToStationId int64 `json:"toStationId"`
}

type _SimpleSection SimpleSection

// NewSimpleSection instantiates a new SimpleSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimpleSection(sectionId int64, fromStationId int64, toStationId int64) *SimpleSection {
	this := SimpleSection{}
	this.SectionId = sectionId
	this.FromStationId = fromStationId
	this.ToStationId = toStationId
	return &this
}

// NewSimpleSectionWithDefaults instantiates a new SimpleSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimpleSectionWithDefaults() *SimpleSection {
	this := SimpleSection{}
	return &this
}

// GetSectionId returns the SectionId field value
func (o *SimpleSection) GetSectionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SectionId
}

// GetSectionIdOk returns a tuple with the SectionId field value
// and a boolean to check if the value has been set.
func (o *SimpleSection) GetSectionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SectionId, true
}

// SetSectionId sets field value
func (o *SimpleSection) SetSectionId(v int64) {
	o.SectionId = v
}

// GetFromStationId returns the FromStationId field value
func (o *SimpleSection) GetFromStationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FromStationId
}

// GetFromStationIdOk returns a tuple with the FromStationId field value
// and a boolean to check if the value has been set.
func (o *SimpleSection) GetFromStationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromStationId, true
}

// SetFromStationId sets field value
func (o *SimpleSection) SetFromStationId(v int64) {
	o.FromStationId = v
}

// GetToStationId returns the ToStationId field value
func (o *SimpleSection) GetToStationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ToStationId
}

// GetToStationIdOk returns a tuple with the ToStationId field value
// and a boolean to check if the value has been set.
func (o *SimpleSection) GetToStationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToStationId, true
}

// SetToStationId sets field value
func (o *SimpleSection) SetToStationId(v int64) {
	o.ToStationId = v
}

func (o SimpleSection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimpleSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sectionId"] = o.SectionId
	toSerialize["fromStationId"] = o.FromStationId
	toSerialize["toStationId"] = o.ToStationId
	return toSerialize, nil
}

func (o *SimpleSection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sectionId",
		"fromStationId",
		"toStationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimpleSection := _SimpleSection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSimpleSection)

	if err != nil {
		return err
	}

	*o = SimpleSection(varSimpleSection)

	return err
}

type NullableSimpleSection struct {
	value *SimpleSection
	isSet bool
}

func (v NullableSimpleSection) Get() *SimpleSection {
	return v.value
}

func (v *NullableSimpleSection) Set(val *SimpleSection) {
	v.value = val
	v.isSet = true
}

func (v NullableSimpleSection) IsSet() bool {
	return v.isSet
}

func (v *NullableSimpleSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimpleSection(val *SimpleSection) *NullableSimpleSection {
	return &NullableSimpleSection{value: val, isSet: true}
}

func (v NullableSimpleSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimpleSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
