/*
RegioJet's Affiliate API Reference

The RegioJet\\'s Affiliate API is a set of endpoints that help your application integrate with RegioJet.  The API is organized arount [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API uses standard HTTP methods, authentication, and status codes.  # Authentication Authentication to the API is performed via [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication) for all endpoints listed in this documentation with the exception of `/users/authenticate`, which uses bearer token.  API requests without authentication will fail.  All API requests must be made over [HTTPS](https://en.wikipedia.org/wiki/HTTPS).  # Errors  RegioJet uses conventional HTTP status codes in responses to indicate the success or failure of an API request.  In general:   * `2xx` codes indicate success;   * `4xx` codes indicate an error that failed given the information provided in request.   * `5xx` codes indicate an error with RegioJet's servers.

API version: 1.1.0
Contact: developers@studentagency.cz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SroPassengersInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SroPassengersInfo{}

// SroPassengersInfo struct for SroPassengersInfo
type SroPassengersInfo struct {
	Passengers []Passenger `json:"passengers"`
}

type _SroPassengersInfo SroPassengersInfo

// NewSroPassengersInfo instantiates a new SroPassengersInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSroPassengersInfo(passengers []Passenger) *SroPassengersInfo {
	this := SroPassengersInfo{}
	this.Passengers = passengers
	return &this
}

// NewSroPassengersInfoWithDefaults instantiates a new SroPassengersInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSroPassengersInfoWithDefaults() *SroPassengersInfo {
	this := SroPassengersInfo{}
	return &this
}

// GetPassengers returns the Passengers field value
func (o *SroPassengersInfo) GetPassengers() []Passenger {
	if o == nil {
		var ret []Passenger
		return ret
	}

	return o.Passengers
}

// GetPassengersOk returns a tuple with the Passengers field value
// and a boolean to check if the value has been set.
func (o *SroPassengersInfo) GetPassengersOk() ([]Passenger, bool) {
	if o == nil {
		return nil, false
	}
	return o.Passengers, true
}

// SetPassengers sets field value
func (o *SroPassengersInfo) SetPassengers(v []Passenger) {
	o.Passengers = v
}

func (o SroPassengersInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SroPassengersInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passengers"] = o.Passengers
	return toSerialize, nil
}

func (o *SroPassengersInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passengers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSroPassengersInfo := _SroPassengersInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSroPassengersInfo)

	if err != nil {
		return err
	}

	*o = SroPassengersInfo(varSroPassengersInfo)

	return err
}

type NullableSroPassengersInfo struct {
	value *SroPassengersInfo
	isSet bool
}

func (v NullableSroPassengersInfo) Get() *SroPassengersInfo {
	return v.value
}

func (v *NullableSroPassengersInfo) Set(val *SroPassengersInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSroPassengersInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSroPassengersInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSroPassengersInfo(val *SroPassengersInfo) *NullableSroPassengersInfo {
	return &NullableSroPassengersInfo{value: val, isSet: true}
}

func (v NullableSroPassengersInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSroPassengersInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
